### PR TITLE
refactor(all): typescript, upgrade to chart.js@3, use npm workspaces

### PR DESCRIPTION
**Pull request by MaximBalaganskiy**
The main goal is to upgrade to chart.js@3, but since I looked into it anyway I took the liberty to upgrade to typescript and npm workspaces.

Cleaned out jspm and aurelia build scripts as well.

### CODE REVIEW

**Comment by grofit** [comment]
I am not too sure about a few of the editor specific things, but rest looks good. If anyone has any problems they can always push another PR detailing what they dislike about it and why etc.

**Comment by grofit** [comment]
While doing package bump I noticed the package.json is marked as private and has a different name `aurelia-chart-monorepo`, are you publishing this separately yourself or are you ok with me just removing private flag and resetting name and doing an `npm publish`?

**Comment by MaximBalaganskiy** [comment]
The actual package is in packages/aurelia-chart folder. Doing it this way
allows for having a demo app as a package as well. Npm than manages the
symlink to the chart package

**Comment by grofit** [comment]
ahhhh ok, I have not used npm workspaces :D good to know they exist now though.

I will update the package version and publish that then, thanks again for the PR.

**Comment by grofit** [comment]
ok not as simple as I thought, what is intended build order here? I assumed:

- `npm i` on root
- `npm run build` on root
- `npm run build` on package (aurelia-chart)

I am getting varying errors though, I am on windows 10 not sure if that makes any issues, but I have an exam to do in a mo, so cant really delve much further til later.

If you could give me the intended build sequence I can push up new version to npm.

**Comment by MaximBalaganskiy** [comment]
I've cleaned up the scripts - `lage` is an overkill here ;)
The sequence is
* `npm i`
* `npm start` (optionally start the demo app to check the changes)
* `npm build`
* `npm run publish:latest`

The version number is in two places - main `package.json` and `aurelia-chart/package.json`. 
You only need to update the first one you would like to automate `changelog.md` updates.

**Comment by grofit** [comment]
Right all published under 0.3.1 thanks again for help

**Pull request merged**
