### PR TITLE
fix main field of package.json

### PR DESCRIPTION
**Pull request by fmal**
Hi,

to use this plugin with [aurelia-webpack,](https://github.com/aurelia/webpack-plugin), the main field of `package.json` should point to `dist/commonjs/index.js`. 
Then it's a matter of specifying the following in your `webpack.config.js`:

``` js
{
  plugins: [
    new AureliaWebpackPlugin({
      includeSubModules: [{ moduleId: 'aurelia-chart' }]
    })
  ],
  alias: {
    'chartjs': 'chart.js'
  }
}
```

This might be something worth adding to the readme :smiley:

### CODE REVIEW

**Comment by grofit** [comment]
Thanks, have merged

**Comment by fmal** [comment]
Thanks, could you publish on NPM?

**Comment by grofit** [comment]
oh yes, will do now for you, just need to bump version etc.

**Comment by grofit** [comment]
done (0.2.4)

**Comment by fmal** [comment]
Awesome, thanks a lot :+1:

**Pull request merged**
