### PR TITLE
Fix for JSPM installation / issue #15

### PR DESCRIPTION
**Pull request by urosg80**

### CODE REVIEW

**Comment by grofit** [comment]
The demo doesnt seem to work in your branch:

https://rawgit.com/urosg80/aurelia-chart/master/examples/jspm/index.html

Could you make sure that works then push up again.

**Comment by urosg80** [comment]
Will check, I tested on my other project but didn't in the example.

 Thanks for checking.

**Comment by urosg80** [comment]
Just did a fix for the jspm example, please check again, this works for me.

**Comment by grofit** [comment]
Merged

**Pull request merged**
